baseurl = "https://askyammer.github.io/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Ask Yammer"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
#  homeTitle = "Ask Yammer" # Set a different text for the header on the home page
  subtitle = "Answers to commonly asked questions"
  logo = "img/SiteWide Images/avatar-favicon.png" # Expecting square dimensions
  favicon = "img/SiteWide Images/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Yammer Support"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

#[[menu.main]]
#    name = "About"
#    url = "page/about/"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
